stages:
  - format
  - build
  - android

clang-format:
  stage: format
  image: suyuemu/cibuild:linux-x64
  allow_failure: true
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/format/script.sh

# comment out for testiang, as takes to long for building
#build-linux:
#  stage: build
#  image: suyuemu/cibuild:linux-x64
#  resource_group: linux-ci
#  variables:
#    RELEASE_NAME: mainline
#  script:
#    - git submodule update --init --depth 1 --recursive
#    - bash .ci/scripts/linux/docker.sh
#    - bash .ci/scripts/linux/upload.sh
#  artifacts:
#    paths:
#      - artifacts/*

android:
  stage: android
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get -y install ccache apksigner glslang-dev glslang-tools git sdkmanager android-sdk bash openjdk-17-jdk openjdk-17-jre curl zip unzip tar cmake ninja-build
    # add clang
    - apt-get install --no-install-recommends -y clang-14 lld-14 llvm-14 llvm-14-linker-tools && ln -s $(which clang-14) /usr/bin/clang && ln -s $(which clang++-14) /usr/bin/clang++
    - export ANDROID_HOME="/usr/lib/android-sdk/"
    - echo y | sdkmanager --sdk_root=/usr/lib/android-sdk --licenses
  script:
    - apt-get update -y
    - git submodule update --init --recursive
    - cd src/android && ./gradlew assemblemainlinerelease bundlemainlinerelease --stacktrace
  artifacts:
    name: "android"
    paths:
      - artifacts/*

#android:
#  stage: android
#  image: ddutchie/linux:latest
#  before_script:
#    - apt-get update
#    - apt-get -y install ccache apksigner glslang-dev glslang-tools git sdkmanager android-sdk bash openjdk-17-jdk openjdk-17-jre curl zip unzip tar
#    - export ANDROID_HOME="/usr/lib/android-sdk/"
#    - echo y | sdkmanager --sdk_root=/usr/lib/android-sdk --licenses
#  variables:
#    GIT_SUBMODULE_STRATEGY: recursive
#    GIT_SUBMODULE_DEPTH: 1
#    RELEASE_NAME: mainline
#  script:
#    - cd src/android && ./gradlew assemblemainlinerelease bundlemainlinerelease --stacktrace
#  artifacts:
#    name: "android"
#    paths:
#      - artifacts/*

