stages:
  - format
  - build

clang-format:
  stage: format
  image: suyuemu/cibuild:latest
  variables:
    RELEASE_NAME: mainline
  script:
    - bash .ci/scripts/format/script.sh

build-linux:
  stage: build
  image: suyuemu/cibuild:latest
  resource_group: linux-ci
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/linux/docker.sh
    - bash .ci/scripts/linux/upload.sh
  artifacts:
    paths:
      - artifacts/*
