stages:
  - format
  - build

clang-format:
  stage: format
  image: suyuemu/cibuild:linux-x64
  allow_failure: true
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/format/script.sh

build-linux:
  stage: build
  image: suyuemu/cibuild:linux-x64
  resource_group: linux-ci
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/linux/docker.sh
    - bash .ci/scripts/linux/upload.sh
  artifacts:
    paths:
      - artifacts/*

android:
  stage: build
  image: suyuemu/cibuild:android-x64
  script:
    - apt-get update -y
    - git submodule update --init --recursive
    - export ANDROID_HOME="/usr/lib/android-sdk/"
    - echo y | sdkmanager --sdk_root=/usr/lib/android-sdk --licenses
    - bash ./.ci/scripts/android/build.sh"
  after_script:
    - cp src/android/app/build/outputs/apk/mainline/release/*.apk ./artifacts
  artifacts:
    name: "android"
    paths:
      - artifacts/*.apk
