stages:
  - format
  - build
  - android

clang-format:
  stage: format
  image: suyuemu/cibuild:linux-x64
  allow_failure: true
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/format/script.sh

# comment out for testiang, as takes to long for building
#build-linux:
#  stage: build
#  image: suyuemu/cibuild:linux-x64
#  resource_group: linux-ci
#  variables:
#    RELEASE_NAME: mainline
#  script:
#    - git submodule update --init --depth 1 --recursive
#    - bash .ci/scripts/linux/docker.sh
#    - bash .ci/scripts/linux/upload.sh
#  artifacts:
#    paths:
#      - artifacts/*

android:
  stage: android
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get -y install ccache apksigner glslang-dev glslang-tools git sdkmanager android-sdk bash openjdk-21-jdk openjdk-21-jre
    - export ANDROID_HOME="/usr/lib/android-sdk/"
    - echo y | sdkmanager --sdk_root=/usr/lib/android-sdk --licenses
  script:
    - apt-get update -y
    - git submodule update --init --depth 1 --recursive
    - bash -c "export PR_NUMBER=$PR_NUMBER; ./.ci/scripts/android/build.sh"
  artifacts:
    name: "android"
    paths:
      - artifacts/*
