variables:
  PR_NUMBER: "pr$CI_MERGE_REQUEST_IID"

stages:
  - format
  - android
  - build

clang-format:
  stage: format
  image: suyuemu/cibuild:linux-x64
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/format/script.sh

build-linux:
  stage: build
  image: suyuemu/cibuild:linux-x64
  resource_group: linux-ci
  variables:
    RELEASE_NAME: mainline
  script:
    - git submodule update --init --depth 1 --recursive
    - bash .ci/scripts/linux/docker.sh
    - bash .ci/scripts/linux/upload.sh
  artifacts:
    paths:
      - artifacts/*

android:
  stage: android
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get -y install ccache apksigner glslang-dev glslang-tools git libboost-all-dev sdkmanager android-sdk bash openjdk-21-jdk openjdk-21-jre build-essential g++ python3-dev autotools-dev libicu-dev libbz2-dev
    - mkdir -p libboost
    - wget https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz
    - tar xvf boost_1_79_0.tar.gz
    - mv boost_1_79_0/* libboost/
    - cd libboost && bash ./bootstrap.sh --prefix=/usr/ && ./b2 && ./b2 install && cd ..
    - export ANDROID_HOME="/usr/lib/android-sdk/"
    - echo y | sdkmanager --sdk_root=/usr/lib/android-sdk --licenses
  script:
    - apt-get update -y
    - git submodule update --init --depth 1 --recursive
    - bash -c "export PR_NUMBER=$PR_NUMBER; ./.ci/scripts/android/build.sh"
  artifacts:
    name: "android"
    paths:
      - artifacts/*
