name: Android CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    if: ${{ true }} # at the moment this simply wastes our minutes, we will enable it when we have unit tests etc.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle


      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon assembleDebug

      - name: Archive release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          retention-days: 5
          path: |
            app/build/outputs/apk/*
